dist: xenial
sudo: required
language: node_js
node_js:
  - "8.12.0"
cache: npm
services:
  - mongodb
before_install:
  - sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev-dev
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - wget https://bitcoin.org/bin/bitcoin-core-0.17.1/bitcoin-0.17.1-x86_64-linux-gnu.tar.gz && cat bitcoin-0.17.1-x86_64-linux-gnu.tar.gz| gzip -d | tar -xv

before_script:
  - yarn global add ganache-cli
  - mkdir -p /home/travis/.bitcoin && cp bitcoin.conf /home/travis/.bitcoin/bitcoin.conf
  - ./bitcoin-0.17.1/bin/bitcoind -reindex -txindex -regtest -daemon -rpcport=18443 -rpcuser=bitcoin -rpcpassword=local321 -deprecatedrpc=signrawtransaction
  - CI=false ganache-cli > /dev/null &
  - export NODE_OPTIONS="--max-old-space-size=8192"
  - cp .env.example .env
  - cp test/env/.env.test.example test/env/.env.test
  - CI=false npm run setup:test_json
  - CI=false npm run deploy:contracts
  - CI=false npm run liquidator:test &
  - sleep 60

jobs:
  include:
    - stage: Test Main
      script:
        - CI=false npm run lint
        - CI=false npm run test:liquidator:liquidate
        - CI=false npm run test:liquidator:refund
