version: '3'
services:
  api:
    build: .
    image: atomicloans/agent
    container_name: agent_api
    environment: 
    - MONGODB_URI=mongodb://db/agent
    - PARTY=lender
    - PORT=3030
    - PROCESS_TYPE=api
    env_file:
    - ./.env
    ports:
    - "3030:3030"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./.env:/app/.env
    command: ["bin/atomicagent", "api"]
  worker:
    build: .
    image: atomicloans/agent
    container_name: agent_worker
    environment: 
      - MONGODB_URI=mongodb://db/agent
      - PARTY=lender
      - PORT=3032
      - PROCESS_TYPE=worker
    env_file:
    - ./.env
    volumes:
    - ./.env:/app/.env
    ports:
    - "3032:3032"
    networks:
      - app-network
    command: ["bin/atomicagent", "worker"]
  db:
    image: mongo:4.2.2
    container_name: db
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:  
